# Generated by Django 2.0.5 on 2020-01-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principle',
            new_name='principla',
        ),
    ]
